Change Download Function
viur-framework/viur-vi pull request #124
Opened 2022-03-31 06:48 UTC by ArneGudermann

Fix File download for Bones.

2022-04-08 17:03 UTC, sveneberth commented
@ArneGudermann Your PR has a merge conflict. Please resolve it to be ready to review and merge.

2022-05-25 15:03 UTC, phorward requested changes
You Pull Request contains several major issues causing direct exception raise. It doesn't seem to be tested before. Please fix your code.

2022-05-25 15:03 UTC, phorward commented on vi/actions/file.py
> +		a["href"] = "/file/download/%s/%s?download=1" % (fileData["dlkey"])
This format-string uses `%s` placeholder two times, but only one parameter is passed. Please use `f"..."`-strings here.

2022-05-25 15:03 UTC, phorward commented on vi/widgets/file.py
> +		a["href"] = "/file/download/%s/%s?download=1" % ( self.currentFile["dlkey"])
This format-string uses `%s` placeholder two times, but only one parameter is passed. Please use `f"..."`-strings here.

2023-03-16 14:51 UTC, closed without merging