first draft of a date range filter for bones
viur-framework/viur-vi pull request #31
Opened 2019-04-06 20:40 UTC by skoegl

Here I would like to introduce a date range filter for dateBones.

SInce only one kind entry is allowed to use $lt or $gt operators in filter, we should also have mutual exclusive filter groups. Here we go

2019-04-07 21:20 UTC, phorward requested changes
Hi @skoegl! 
This looks good to me, can you please change the commented lines and add translations?

2019-04-07 21:20 UTC, phorward commented on bones/date.py
> +		self.modul = modul
please rename "modul" into "module"

2019-04-07 21:20 UTC, phorward commented on bones/date.py
> +		fromLabel = html5.Label("Startdatum")
Please provide `translate("begin date")` or something similar and put appropriate translations into translations/de.py

2019-04-07 21:20 UTC, phorward commented on bones/date.py
> +		toLabel = html5.Label("Enddatum")
same here (translate)

2019-04-07 21:20 UTC, phorward commented on bones/date.py
> +		self.clearButton = html5.ext.Button("Filter entfernen", self.clearFilter)
translation

2019-04-07 21:20 UTC, phorward commented on bones/date.py
> +		print("updateFilter", self.extension["target"], filter, mutualExclusiveGroupTarget)
please remove / convert into comment

2019-04-07 21:20 UTC, phorward commented on bones/date.py
> +		print("clearedFilter before new values", self.extension["target"], clearedFilter)
comment out

2019-04-07 21:20 UTC, phorward commented on bones/date.py
> +		print("clearedFilter result", self.extension["target"], clearedFilter)
comment out

2019-04-09 20:46 UTC, skoegl commented
I'm myself not completely satisfied with this PR. We should discuss especially the mutual exclusive group thing in our next viur meeting or here. Alternatively it works fine for now, so let's accept to get this feature into develop and discuss improvement in a next PR.

2019-04-10 13:10 UTC, phorward commented
> Alternatively it works fine for now, so let's accept to get this feature into develop and discuss improvement in a next PR.

That's a good deal. I'm also of the opinion that new feature should be made available ASAP... improvements and perfection can be done later. I will take a look at it how it's generally running in the next few days and then merge it into dev.

2019-04-10 13:10 UTC, phorward approved these changes

2019-05-08 12:48 UTC, merged