Fixing problem that time "00:00:00" is passed
viur-framework/viur-vi pull request #32
Opened 2019-04-15 14:08 UTC by phorward

This is the case when serializeForPost() is called with an empty date and with time=False, but a time is returned?

2019-04-15 14:13 UTC, skoegl approved these changes

2019-04-17 14:09 UTC, sveneberth approved these changes

2019-04-17 14:09 UTC, sveneberth requested changes
Please add the changes to the CHANGELOG

2019-04-17 14:51 UTC, sveneberth approved these changes

2019-04-17 17:37 UTC, merged